anoadragon453/busty

main.py

Actually use the discord @mention feature instead of just printing users' Discord nick/name in plaintext

Mention users in !list and when playing their song

---

main.py

Automatically pin tracklist from the `!list` command

Automatically pin tracklist

---

README.md
main.py

Closes #1 by allowing configuration via environment variables.
The list of environment variables added are
1. `BUSTY_DISCORD_TOKEN` - Discord bot API token (required)
2. `BUSTY_COOLDOWN_SECS` - Number of seconds between songs (default = 10)
3. `BUSTY_ATTACHMENT_DIR` - Directory to save attachments (default = attachments)
4. `BUSTY_DJ_ROLE` - Name of role with permissions to run commands (default = bangermeister)

Add environment variable configuration

---

main.py

I missed this in the review of #5, my bad!
* One of exception types was not imported (`NotFound`)
* One of them had a typo (`HttpException`)

Fix importing a couple exceptions

---

main.py

Change the output of the !list command from a regular Discord message to an embed. Additionally, turn song names in output into hyperlinks directly to the message the song was originally sent in.

Revamp !list command output

---

main.py

Add color `#dd2e44` to the result of the !list command. This is the same color Discord uses for the heart part of the flaming heart emoji used in the same command.

Add color to !list

---

main.py

Fixes Issue #16 by handling the case when attachment.content_type is None

handle if attachment.content_type is None

---

main.py

Uses the same embed color as the `!list` command

Make "Thanks for coming" message an embed

---

main.py

Recover on TinyTagException

---

main.py

Closes #72. Adds a reminder to vote onto the "Now Chillin'" message which plays before every song.

Add reminder to vote

---

dev-requirements.txt

This fixes the issue which would cause black to raise an exception: https://github.com/psf/black/issues/2964

Update black to 22.3.0

---

main.py

Just in case we take a while to start, and people are talkative.
This doesn't appear to have any real performance impact.

Up the message scanning limit to 1000

---

main.py

Since we have a 0 voting option, we should make sure every vote is consciously chosen.

Make voting required for all questions

---

main.py

Simple but effective. If any characters of the `current_channel` pass Python's `isdigit()` check, they are all concatenated together into a string _N_ and the voting form is titled "Busty's _N_ Voting". If there are no digits, the default title "Busty's Voting" is used.

Title Google form based on bust # in channel name

---

main.py

Closes #68. When the bot is killed during a bust, it will now reset its nickname and unpin the "now playing" message of the currently playing song. ~Some changes may conflict with #78, but if so they should be easy to manually resolve~.
For catching the quit event, [nextcord.onclose()](https://docs.nextcord.dev/en/stable/api.html?highlight=exit#nextcord.on_close) was used as [suggested](https://github.com/anoadragon453/busty/issues/68#issuecomment-1166376821). To reset nickname `finish_bust()` is called without the goodbye message. A new global variable was added that keeps track of the currently pinned "now playing" message so it can be unpinned in the close event, since when a kill signal is sent the task that would normally unpin the "now playing" message is never revived again.

Cleanup nickname + pins on interrupt

---

main.py

Closes #111. Automatically generates a comments/suggestions section instead of having to do it manually every time, taking up precious time between list and bust start.

Add comments/suggestions to voting form

---

src/config.py
src/main.py

So we read all env variables in the same place

Move Discord token to config.py

---

src/forms.py

Make all questions on voting form required (except for comments/suggestions) just like when we were using Apps Script. Has been tested.

Make all questions required

---

src/bust.py
src/config.py
src/song_utils.py

Closes #128, moved two constants to `constants.py`.

Refactor some constants to constants.py

---

README.md
src/bust.py
src/config.py
src/main.py

Closes #134. Must be used after `/list`. In case you were wondering, the @ mention DOES work even when the user is not in the channel or even on the server anymore.

Add /info command

---

src/main.py

This likely has merge conflicts with some currently waiting pull requests, but it's simple enough that with approval I'll just merge in and push myself after those are pushed.

Add some missing periods where they should be

---

requirements.txt
src/main.py

Updating nextcord version to 2.4.1 as well as a better description for wrong media types in uploaded files for `/preview`

Update Nextcord Version to 2.4.1

---

src/bust.py
src/llm.py
src/main.py

Busty will now know when the bust is currently happening and the song name.
I moved the guild.id --> BustController map into `bust.py` so it can be accessed by anything that imports it, including `llm.py`. As a result I also had to rename the `bust()` function in `main.py` so the imported `bust` module could be accessed.
We could turn off her random responses during the bust message spam but I think it might be funnier if we test not doing that for this time

Make LLM bust-aware

---

src/main.py

Remove periods to show image preview

---

requirements.txt
src/llm.py

Update OpenAI library to 1.1 release, which had breaking changes.

Update OpenAI library

---

src/bust.py
src/llm.py
src/song_utils.py

Resolves #198. Generate album art if OpenAI key is available and track has none embedded.
Will time out generation after 20 seconds.

Add DALL·E 3 cover art generation

---

src/llm.py

Add a missing await

---

dev-requirements.txt

Been a little while since we did this. Happy thanksgiving.

Update pinned dev dependencies

---

src/emoji_list.py

imo these are funny and fit busty's personality
also flags was listed twice in the comment about which categories we removed

Allow so-called "mood killer" emoji

---

requirements.txt
src/main.py

This PR allows busty to compile and run on NextCord 3.0.0+.

NextCord 3+
