- main.py
We should exit `play_next_song` early upon running out of songs. Otherwise we'll just go ahead and try to queue up the next song, as well as say "Chilling ..." when the show is over.
> Add a missing return upon running out of songs to play

- main.py
Partially addresses #3. This PR sets Busty's nick to that of the currently playing song. Her original nick is restored after playback has concluded. It looks like:
Only partially addresses, as adding an emoji to the name will be done in a separate PR (I'm thinking of pulling the set of allowed emoji from a configurable text file).
Reviewable by commit, although there's only 2.
> Set the bot's nick to that of the currently playing song

- .github/workflows/lint.yml
- main.py
- scripts-dev/lint.sh
- setup.cfg
This PR adds linting for continuous integration to the repo, defined by the [.github/workflows/lint.yml](https://github.com/anoadragon453/busty/blob/anoa/lint_ci/.github/workflows/lint.yml) file. It also adds a bash script at [scripts-dev/lint.sh](https://github.com/anoadragon453/busty/blob/anoa/lint_ci/scripts-dev/lint.sh), which is useful for linting your code just before you commit. This also ensures that CI will pass before creating a PR.
The linting tools that are run are:
- [isort](https://pypi.org/project/isort/) - sorts import statements
- [flake8](https://pypi.org/project/flake8/) - lints and finds mistakes
- [black](https://pypi.org/project/black/) - opinionated code formatter
I'm open to opinions on including others! Settings for each are defined in `setup.cfg`.
Note that these …
> Add linting CI to the repo and a lint script for local checking

- .github/workflows/lint.yml
I pulled the CI config from an older repo of mine which had `master` as the default branch name, rather than `main` which we use here (and is now default across new GitHub repositories).
> Fix master -> main default branch name in CI config

- main.py
Fixes #20.
In a couple different places, we wanted to get either Busty bot's current server nickname (`Member.nick`, if one was set), or if not, the bot's canonical name (`Member.name`).
Forgetting to use `Member.name` if `Member.nick` was `None` lead to a bug that caused #20.
Instead, we should just use the [`discord.Member.display_name`](https://discordpy.readthedocs.io/en/latest/api.html?highlight=member#discord.Member.display_name) attribute, which is effectively the same, but less prone to mistakes.
> Replace instances of member.nick or member.name with member.display_name

- main.py
Resolves Issue #2.
Make the "Now Playing" and waiting messages rich text embed for better visibility. Also add a number of other features like
- Direct file jumping (like in !list)
- Direct message jumping (like in !list)
- Re-posting text sent with original submission
Also includes a slight internal restructure. The return tuple of the `scrape_channel_media` function was getting bloated, so it now keeps direct references to the original message and attachment from which most previously included fields can be derived.
> Revamp "Now Playing" and "Chillin" messages

- main.py
Currently we print song titles as the names of the files attached. To make them look nicer, we can
- Drop the file extension
- Replace underscores with spaces
I've attached an image where I did some experimentation and concluded that Discord does not allow filenames starting with underscores, so we should not get any "empty" song names this way. Currently multiple spaces seem to be consolidated to one space. I'm fairly sure this is an issue with the way Discord renders the embed and not anything in this code, but there might be a way to fix it.
I think needing to maintain the exact number of underscores as they convert to spaces is such an obscure use case we can ignore it for now (or forever).
> Format filenames more nicely

- .gitignore
- main.py
- requirements.txt
* When the command is `!list`, the output will have audio title, artist, album in the format `title | artist | album`
* If the media does not have the specified tags, the filename will be used instead
* `!list command`
* `!play command`
Solves the issue #25
> Solved: Read media info from tags 

- main.py
Closes #37.
Allows calling `!list <channel mention>`. This what the output message would be if you called `!list` in the mentioned channel, but sends the message in the same channel that the command was called from. The output of `!list` is now only pinned if the channel the command was called from is the same as the channel being listed.
> Allow !list with target channel

- main.py
Discord embed descriptions have a 4096 character limit ([source](https://discord.com/developers/docs/resources/channel#embed-limits)). The `!list` command can exceed this limit, so to circumvent this we split into consecutive embeds, then pin them in reverse order so they appear in the proper order in the channel pins.
> Split !list to avoid 4096 embed char limit

- main.py
When the bot is not currently connected to a voice channel or stage, `active_voice_channel` will be `None`. Thus, using `active_voice_client.is_playing()` will fail.
This PR adds an additional check to ensure `active_voice_channel` is non-None before checking `is_playing()`.
> Prevent an exception when using `!skip` or `!stop` outside of a bust

- main.py
Fixes #34 
If the playlist is already being consumed, `!list` is disabled. This is done by checking if the bot is in a voice channel.
> Prevent executing !list while busting

- main.py
Implements #32.
Works internally by generalizing previous tag-aware formatting function `format_filename` (now nameed `song_format`) to allow a "fallback artist name" which if not passed is unused. Markdown escaping is also removed from inside the function Then:
- To format correctly in !list and the next song message, we don't pass a fallback artist and markdown escape the result.
- To format correctly in the nickname we pass `author.display_name` of the song submitter as the fallback artist name.
In reorganizing the function, incidentally a parameter `local_filepath` has been added (separate from `filename`, the filename on Discord itself). The previous version of the function assumed that the local filepath was always `<media directory>/<discord filename>`. This is true for now, but …
> Make nickname string tag-aware

- main.py
Looks like I missed this in the initial implementation.
`current_channel` is the text channel that we intend to send messages/embeds in.
> Add missing type annotation for 'current_channel'

- main.py
Closes #31.
Instead of saving files with the filename direct from Discord, use the name `(Track #).(Discord Filename)` where the track number is formatted to be exactly 3 digits. Recall that busty only reads the first 500 messages, so 3 digits is sufficient. For ex the 7th song `my_song.mp3` would be saved as `007.my_song.mp3`.
> Save files with unique filenames

- main.py
- requirements.txt
Closes #48.
Rather than allowing users to send as large a file as they'd like, cover art filesize is capped to 8MB, or 8 million bytes. This is less than the actual Discord cap of (about) 8MiB, though the Discord cap CAN rise if the bot is in a boosted server.
Since the time take to upload the cover image does cause message latency, and since there's really no reason anyone needs cover art over 1MB let alone 8, I think this is a good cap (I'd even be ok lowering it).
This commit adds a dependency to Pillow, solely because we need to know which file format the cover art is, and it seems neither Discord nor TinyTag can detect this themselves. We are using such a small part of the Pillow library that it shouldn't be too difficult to eliminate this dependency by checking some magic bytes …
> Read cover art from audio files

- main.py
Fixes #54.
Messages over 1024 characters are truncated in "More Info" to 1023 chars plus the `…` character.
> Truncate long messages in "More Info"

- README.md
- main.py
- requirements.txt
Closes #53. While nextcord recommends changing the import from "import discord" to "import nextcord" it's not required, and I have not done so here. As far as I can tell they don't plan on removing this alias anytime soon, so I think think should keep it for now in case we need to move back to discord.py or over to pycord.
Incidentally, I've also changed the TinyTag dependency from =1.7.0 to >=1.7.0 to be in line with the other dependencies which all have only a lower bound.
> Update requirements (discord.py --> nextcord)

- main.py
Implements #52 
A copy of list of attachments is generated when running `!list`. This list is held until the current bust ends, in which the list is enumerated and each attachment is removed from disk. This list is overwritten if `!list` is called multiple times before `!bust`.
> Remove attachments from disk on end of bust

- main.py
`tags` is not used later anyhow.
> Log when reading the tags of a file failed

- main.py
Fixes #64.
From this:
To this:
1000 characters for either a song or title was chosen arbitrarily. With both, the output would look like:
which is kind of long, but still within the range of what I'd consider funny over bot-breaking.
> Sanitize user-provided artist and title tags if found

- main.py
Fixes #70 
Introduced in https://github.com/anoadragon453/busty/pull/42. Missed this during code review :sob:
> Check for the presence of one or more arguments, not >1

- main.py
Closes #73. During Busty's 3, a certain [mp3 file](https://cdn.discordapp.com/attachments/938166238193025124/938258064224714752/ImAGhost.mp3) caused busty to hang forever. The reason was because in the `get_cover_art()` function, the `audio` variable tested True for `isinstance(audio, ID3FileType)` but `audio.tags` was `None`. From what I can tell, this is a bug in mutagen itself, as the [documentation](https://mutagen.readthedocs.io/en/latest/user/classes.html?highlight=filetype#tags) seems to suggest that this field should always be of type `Tags`. This PR checks that attributes of MutagenFile are not `None` before using them.
> Fix audio.tags nonetype bug

- README.md
So that new contributors have an easier path forwards.
Instructions on installing the dependencies to run `./scripts-dev/lint.sh` are intentionally excluded, as they are added in https://github.com/anoadragon453/busty/pull/86 instead.
> Add development documentation to the README

- .github/workflows/lint.yml
- README.md
- dev-requirements.txt
The result of this is that one no longer needs to dig into the CI config in order to figure out how to run the linting script.
Depends on https://github.com/anoadragon453/busty/pull/85. Reviewable commit-by-commit.
> Add a requirements.txt equivalent for dev dependencies

- main.py
I typed `!List` once so I wrote this PR.
This change modifies the content of messages before we check for commands, by:
* lowercasing the text, allow case-insensitive commands to work
* stripping surrounding whitespace
The latter operation may not actually be required, as Discord looks to try and do this itself already. But it's a cheap check, and people may be using different clients.
> Allow case-insensitive commands, and strip surrounding whitespace

- README.md
- main.py
Partially implements #12. The `!form` command (when run after `!list`) prints out Google Apps Script code which can be copied and pasted to automatically generate a voting form from the Apps Script code editor in your browser.
There is still in theory work to be done on this front, for example automatically generating the responses form and statistics, or even using the Google API to generate the form without any manual copying and pasting. However, this implements 95% of what would be nice to have, and is a self-contained feature.
> Google Form generation with Apps Script

- main.py
Resolves #75. Incidentally, also resolves #65.
Saved files in attachments directory with the name `<message_id>.<attachment_id>.<original_extension>`. If a file with this name already exists in the directory, a new one is not downloaded. After we ensure all files for the current list are there, we delete all files not on the current list.
To prevent anything spooky like async invocations deleting each other's files, an async lock is wrapped around the `command_list` call. In the future, it might be a good idea to allow `command_list` to be interruptible instead, as there's no reason to let one `!list` command finish if another is going to run immediately after.
In order to have caching function properly, files are no longer deleted after a bust ends either.
> Cache files from previous !list invocations

- main.py
Closes #83. Gives the user feedback if they `!bust` while a bust is happening.
> Feedback on !bust while busting

- dev-requirements.txt
- main.py
- pyproject.toml
- requirements.txt
Reduces the number of type errors found by [mypy](https://mypy.readthedocs.io/) across the codebase.
Takes us from:
<details>
<summary>before this PR</summary>
```
(venv) [user@izzy busty]$ mypy main.py --show-error-codes
main.py:9: error: Skipping analyzing "mutagen": module is installed, but missing library stubs or py.typed marker  [import]
main.py:9: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
main.py:10: error: Skipping analyzing "mutagen.flac": module is installed, but missing library stubs or py.typed marker  [import]
main.py:11: error: Skipping analyzing "mutagen.id3": module is installed, but missing library stubs or py.typed marker  [import]
main.py:12: error: Skipping analyzing "mutagen.ogg": module is installed, but missing library stubs …
```
> Fix a number of type hint errors

- main.py
I ran `!list` on a channel with all Busty's 4 songs with versions of Busty which:
1. Started all async downloads simultaneously and then waiting for them all to finish (this commit)
2. For each async download, started it and then `await`ed for it to finish before moving to the next download
I cleared the attachments folder in between runs of each version to avoid caching speedups. I performed this entire process about 5-6 times, each time comparing the time of the download phase of both (1) and (2).
While my testing approach was maybe slightly unscientific version (1) was *always* faster than (2) (usually ~9 seconds total download time vs ~12).
> Download files concurrently

- main.py
Closes #101. Adds a hard-coded volume multiplier. ~Currently marked as draft because I cannot find the optimal multiplier myself, as the clipping issue seems to only be reproducible on Windows. At some point I'll get in call with a Windows user to figure this out.~
Bobby and I found that the moment clipping becomes unnoticeable was setting the coefficient just over 0.5, so I set it to 0.5 since it seems like the type of number that whatever technical error is happening would actually need. Despite the volume multiplier being 0.5 down from 1, the audio is actually subjectively barely different in volume (some psychoacoustic log scaling something something).
> Add volume multiplier to avoid clipping

- README.md
- main.py
As of August 31st 2022, Discord will require bots to register an explicit intent in message content in order to receive it. The current beta versions of nextcord will thus only return an empty str for `Message.content` unless the `message_content` intent is enabled. See https://docs.nextcord.dev/en/latest/intents.html#what-happened-to-my-message-commands for further details.
This change allows the bot to function on nextcord>=v2.0.0b1.
> Request the "message content" intent

- main.py
Separated out from #78 in order to reduce the number of changes to reason about. The only change is that #78 originally added `cleanup` and `finish_bust` functions. However, the loop for cleaning up local files has these days been moved to when we scrape files, rather than end a bust. After removing that, the remaining `cleanup` function was quite short. So I inlined its contents into `finish_bust`.
As far as what behaviour this PR changes versus the current cleanup tasks of today; we now set `active_voice_client` and `original_bot_nickname` to `None`. #78 did this as well, and I think it's a reasonable change (else there's old bot state lying around).
Testing locally by letting a bust run its course and using `!stop` both worked as expected (bot's name originally restored, subsequent …
> Factor bust cleanup tasks to a separate function

- README.md
- main.py
This PR:
* Has the google appscript create (and name) the form itself, instead of needing to create one manually first.
* Adds the image itself. Use `!form link_to_gdrive_image` when using the form command.
* Prints links to the editable version of the form, and the public version, for easy sharing.
* Adds syntax highlighting to the code. This isn't necessary, but is nice if you need to quickly scan the golfed code for any reason.
After this PR, the workflow for creating a form is:
1. Pick an image from google drive (right click on the image->get link->copy link)
2. Run `!form https://drive.google.com/file/d/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/view?usp=sharing`
3. Copy/paste the code into [a new google appscript file](https://script.google.com/home)
4. Save and Run (Ctrl-S, …
> Create the whole form automatically

- src/config.py
It turns out the single "logic change" in #125 had a bug I didn't notice, it was using emoji names instead of emoji themselves.
> Fix emoji display

- src/song_utils.py
Closes #124. Creating a mutagen `File` object can return `None` without throwing a `MutagenException` when mutagen cannot determine the filetype ([see code](https://github.com/quodlibet/mutagen/blob/master/mutagen/_file.py#L302)). For some files, this can cause Busty to crash on `!list` when attempting to load tags.
> Fix webm crash

- src/bust.py
- src/main.py
- src/voting.py
Taking some steps to move towards a more modular BustController. BustController should only be instantiated via a new `bust.create_controller()` method, which either constructs a valid controller or returns None. Bust state can be checked externally with the `BustController.active()` function.
Three optional variables still remain in BustController, but for now these all make sense as optional as they move in and out of existence throughout the BustController's lifecycle.
The code which calculates total song length has been moved to the BustController constructor, whereas previously it was in the list command (which has largely become the create_controller function). A few other things like whether there is an active lock are now checked within create_controller as well.
Management of …
> Decouple BustController

- src/forms.py
Just small organization improvement, set document title with form title on form creation, instead of creating it with a random name and tying rename to the success or failure of the document move operation.
Not totally sure why "info.document_title" and "name" refer to the same thing, but it's what the documentation claimed, and it worked in testing.
> Set doc name on form create, not form move

- src/song_utils.py
Fixes https://github.com/anoadragon453/busty/issues/139
`bool(MutagenFile)` can resolve to `False` even if the file was read correctly, as `MutagenFile` inherits from [DictMixin](https://github.com/quodlibet/mutagen/blob/00aba6abfecc5353b6a51b6fa4e382ab57430b7c/mutagen/_util.py#L431-L445) (and `bool({})` resolves to `False`).
Fix the song length calculation by ensuring we check whether audio is explicitly `None`, rather than just falsey.
> Fix a bug where some songs would be skipped during total song length calculation

- .gitignore
- README.md
- src/config.py
- src/main.py
- src/persistent.py
Added a new class PersistentString, which keeps the state of an `Optional[str]` variable in a passed filepath. If the file exists when an instance is created, the string contents are loaded from file. Otherwise, they are none. Whenever the string is set, the file is either written to or deleted depending on whether the string is `None` or not.
Made `loaded_image` a PersistentString, with filepath pointed to by either env var `BUSTY_IMAGE_STATE_FILE`, or with a default value of `.image_state`.
There are a number of different ways this could have been engineered, lmk if you can think of a nicer one and we should do that. This solution seems simple and small enough that it wouldn't be too hard to replace it with something more generic and robust later if we want to start keeping other …
> Make loaded image persistent across reboots

- src/bust.py
Closes #123.
Currently, the playback architecture treats the list of songs like a queue, popping each one off the front in a chain of coroutines which each call each other until the queue is empty.
This PR refactors it so that the list of songs is immutably traversed with a for-loop, and each playback event is a single coroutine call which returns when complete. This leads to a more modular and conceptually simpler control flow with less nonobvious "cleanup" corner cases. surrounding skipping and cancellation.
> For-loop refactor

- src/bust.py
- src/main.py
Currently if you /bust a channel that is NOT the list channel, busty will still send messages in the listed channel. This commit changes that behavior so that the bust messages happen in the channel /bust was ran in.
> Send bust messages in command channel, not list channel

- src/main.py
This commit adds an `/announce` command which lets admins send an embed as the bot into any channel with a given title and body.
You can optionally specify a channel to send the announcement in. If a channel other than the current channel is specified, then the bot will respond with an ephemeral message confirming success of the action. If the current channel is specified, then no ephemeral message will be sent (as the admin will immediately see the announcement anyways).
> Add a command which lets admins send announcements as the bot

- src/bust.py
Busty crashes on `/info` if `get_song_length()` returns None (which it can). Instead, we should treat that song's length as zero and report that statistics may be inaccurate due to errors.
To deal with the unlikely but possible case that ALL songs have errors, we introduce a "phantom submitter" which is the bot member herself, with a total submission length of zero.
> Handle song length errors without crashing

- src/main.py
`interaction.response.send_message` is a Coroutine, so should be `await`d when called.
Missed in https://github.com/anoadragon453/busty/pull/153.
> Fix a missing await on `interaction.response.send_message`

- src/bust.py
As suggested by @anoadragon453 in https://github.com/anoadragon453/busty/pull/154#pullrequestreview-1241376211. Cleaner way to handle the case when no songs with readable length have been submitted.
> Better internal error handling for bad song len

- src/main.py
By setting the [dm_permission](https://docs.nextcord.dev/en/stable/api.html#nextcord.Client.slash_command) argument of `@slash_command` to False, we can prevent commands from being usable in DMs to the bot.
I don't think there's any reason for these to be exposed in DMs, and most of them assume they're being run in a guild anyways.
> Prevent commands from being usable in DMs

- README.md
This PR expands the documentation for setting up a Google Service Account for the Google form generation functionality, as I just struggled a bit when setting it up for the first time with the current docs.
> Update README with more detailed Google Service Account instructions

- .gitignore
- README.md
- src/config.py
- src/main.py
- src/persistent_state.py
This PR adds the ability to store arbitrary persistent state (survives across bot restarts), backed by a JSON store on disk. The store's location can be configured via the `BUSTY_BOT_STATE_FILE`, and defaults to `bot_state.json`.
State can be stored via `persistent_state.set_state(path, value)` and retrieved via `value = persistent_state.get_state(path)`. You can also delete state via `persistent_state.delete_state(path)`. Deleting state at a path will also clear any parent paths that have no state left in them after the delete, in order to keep the store neat and tidy.
The plan is to replace `BUSTY_IMAGE_STATE_FILE` and `PersistentString` with this persistent store implementation.
> Store persistent bot state in a json file with a configurable path

- src/persistent_state.py
Right now if there is no bot_state.json, Busty's won't start. This is bad because the initial run will have no bot_state.json. This PR changes it so that if reading the bot_state.json file fails, a warning is printed and the bot continues with empty state.
> Don't crash when starting with no bot state file

- src/bust.py
- src/main.py
Just some nice cleanup, we use discord emoji format in emoji_list.py and it was a bit ugly having in-text emoji mixed into an otherwise ascii codebase
> Remove in-text emoji, use discord emoji format

- src/bust.py
- src/forms.py
- src/main.py
Closes #171.  Any commands which could potentially take a long time* are now deferred. Also, I've refactored so that when an interaction is passed to a bust controller function it can be assumed to be handled "within" and that bust controller function never returns with an non-replied-to interaction. Defer, error-handling, and "OK" interaction replies are now in the bust controller.
* Technically when saving persistent states file write could take a very long time, but I didn't defer those. Also I guess your CPU clock could be reeeeeally slow....
When using `interaction.response.defer()` your one initial interaction allowance is spent, so you have to use `interaction.followup.send` instead of `interaction.response.send()` afterwards.
> Defer potentially long commands

- src/discord_utils.py
- src/main.py
Closes #148.
The main changes are
1) Turn attachments directory format in `build_filepath_for_attachment()` from `<attachment_dir>/<message_id>.<attachment_id>.<extension>` to `<attachment_dir>/<guild_id>/<attachment_id>.<extension>`.
2) Move clearing useless cached files above the code for downloading new files, to save on disk space
3) In `main.py`, remove the `get_controller()` method, which was a hack since we could not previously have a BustController remove itself from the guild_id --> BustController map after busting. Now that BustController.play() returns only after the bust is complete we can do it ourselves.
Thankfully the persistent_state module was written with multiserver in mind, so no changes needed to be made there. This has all been tested to the best of my abilities.
> Add multiserver support

- src/discord_utils.py
- src/song_utils.py
Closes #162, where Mutagen overweights file extension in guessing filetypes. With this we can finally retire the `ugly_info_fix` branch.
There are basically three solutions to this problem that I can think of.
1. Solve the problem upstream in Mutagen. The most morally righteous, but would may require navigating some pushback and take time to get merged and released
2. Detect better file extension (with magic/guessing/using default ext with no hints), symlink using that extension, and pass the symlink to mutagen. Variants for doing this every time, only if reading fails, etc etc. All of these are a little ugly and hacky in my opinion.
3. ⭐ What this PR does, remove file extensions when we save attachments in the first place. FFMPEG should have no issue determining file formats without an …
> Fix issues with Mutagen file detection

- src/bust.py
/info was accidentally made ephemeral in #172 because it was deferred ephemerally.
> Fix /info being ephemeral

- src/llm.py
This PR fixes a spot where we assumed that an `info` block was always available for a user. This code was only hit in 5% of the responses, so we didn't catch it during testing.
> Fix bug where busty would occasionally assume there was info for a user

- src/config.py
- src/llm.py
OpenAI updates models by first allowing you to to upgrade manually, then eventually upgrading the pointer from the stable version. Because of this it would be nice to be able to keep the stable version as the default value, but allow environ variable configurability for easy upgrade. See screenshot from OpenAI new model announcement email below
> Make OpenAI model configurable via environ variables

- src/bust.py
We recently had an issue where Busty crashed mid-bust. This doesn't fix that, but it does fix another issue we found afterwards where if we listed from another channel (bod dev channel), it would continue to send messages from the channel we listed from, even if /bust was issued elsewhere (the mailbox).
This PR makes it so that the message channel (where messages are sent) gets updated whenever /list OR /bust is run.
> Switch message channel to where bust command is issued from

- src/bust.py
- src/main.py
Add replay command, which may or may not incidentally help recover from crashes, not that we ever have those or anything.
Done by changing the for-loop for songs to a BustController-wide index which is incremented each time, and which can be manipulated when playback is cancelled. Also removed async from BustController `stop()` function since idk why it was there.
Merged code for skip and replay. Could even merge in stop if we just make stop a "skip" to track index of len(bust_content)? But idk if that's confusing. Have tested skip/replay/stop and they all work fine at both index 0 and index nonzero. Made code generic so implementing a `/skip <num>` with a number argument would be ez. We can give it to an intern.
> Add replay command

- src/llm.py
While it was initially thought that busty should randomize her response length, in practice
1) the long ones are way too long, and
2) they don't seem to have that much effect beyond her first message.
We should just remove this randomized context feature unless we need it again, and put "don't be too wordy" in 
`llm_context.json` instead. In fact, the production version has been running a branch modified to only insert "don't be too wordy" and comment the others out, so there's really no need to keep this in.
> Remove random context

- .gitignore
- flake.lock
- flake.nix
This PR adds a [Nix Flake](https://zero-to-nix.com/concepts/flakes) to the repo, which will install and make available all the dependencies needed to develop the busty bot in a single command:
```
nix develop --impure
```
To use this, [install nix](https://github.com/DeterminateSystems/nix-installer#the-determinate-nix-installer) on your system and run the command above. Python 3.11 will be installed, along with ffmpeg, and a virtualenv will be created at `.venv/`. You'll be dropped into a shell with the [starship prompt](https://starship.rs/) (mostly because I think it looks nice). Exit the shell, and all installed programs will no longer be available - truly isolated developer environments!
This all works thanks to [nix](https://nixos.org/), and works on Linux and MacOS. On Windows, it …
> Add a nix flake to the repo

- requirements.txt
Closes #205. Now that mutagen has had an [official release](https://github.com/quodlibet/mutagen/releases/tag/release-1.47.0), the PR we submitted (https://github.com/quodlibet/mutagen/pull/601) to properly detect extensionless ID3-less mp3s is in the repo version, and we no longer need to depend on the git release.
> Change mutagen dependency from git to release

- src/llm.py
the OpenAI API has a lot of [error codes](https://platform.openai.com/docs/guides/error-codes). Surrounding the part where we query the LLM, we have a blanket `catch Exception as e` block. We tried to catch the one specific exception we saw around the DALL-E call but we didnt catch another one which caused Busty to crash last bust due to OpenAI API outages.
I can sympathize with the fact that it's somewhat sketchy to catch all exceptions, but ultimately this is a non-critical feature with the potential of killing the bust if an exception slips through, and catching like 10 different Exception types explicitly all in a row seems overkill and ugly for this project.
If someone disagrees feel free to add your own error handling in a separate commit, but I think #1 priority should be guarding …
> Catch all exceptions when generating album art

- src/persistent_state.py
Busty crashes due to this unbound variable on line 28 if you have no state file.
> Fix unbound bot_state_str variable on first load

- src/bust.py
- src/config.py
Closes #188. This was originally just an idea for fun, but then things got real when we were explicitly asked.
Preview image (has also been tested when # of submitters is less than # to be shown)
> Show a configurable number of top submitters

- src/main.py
Fixes #196 
Nextcord uses the logging module to log all events. Without the logging module setup, errors and such will just be swallowed. This PR uses recommended settings from https://docs.nextcord.dev/en/stable/logging.html, but to stderr instead of a file.
It's getting a little ugly doing so much setup at a global level, so I plan to do some refactoring of `main.py` in another PR. I also may switch our current print logging to the logging module. But for now I think this as important change to make so we can catch future errors.
> Add logging module
